pak::pkg_install('iai')
# pak::pkg_remove('iai')
library(iai)
install_julia()
# iai:::iai_run_julia_setup()
install_system_image(accept_license = TRUE, replace_default = TRUE)
debugonce(install_system_image)
iai:::sysimage_default_install_dir()
iai:::get_machine_id()
